apiVersion: apps/v1
kind: Deployment
metadata:
  name: qrcode-deploy
  labels:
    app: qrcode
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qrcode
  template:
    metadata:
      labels:
        app: qrcode
    spec:
      containers:
        - name: qrcode
          image: qrcodegenerator:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: JAVA_OPTS
              value: "-XX:MaxRAMPercentage=75 -XX:+ExitOnOutOfMemoryError"
